### ISSUE TITLE
Модуль AutoRss

### ISSUE THREAD

**Issue by ssmirenkov** [dle-modules/DLE-AutoRSS#1]
Здравствуйте!
Скачал модуль AutoRss, установил, настроил канал (во вложении скрин).
Жму на кнопку тест и мне выдает вот это

Fatal error: require_once(): Failed opening required 'C:\OpenServer\domains/engine/modules/autorss/autoloader.php' (include_path='.;c:/openserver/modules/php/PHP-5.5;c:/openserver/modules/php/PHP-5.5/PEAR/pear') in C:\OpenServer\domain\autorss.php on line 73

Тестирую на локалке.

Подскажите что не так делаю!
Спасибо!

https://pafnuty.omnidesk.ru/attachment/download/da5b83e9eb82139e08c981a5f16b65e9/801911

**Comment by pafnuty** [comment]
Попробуйте https://github.com/dle-modules/DLE-AutoRSS/commit/e401d0e8ad9af0914c66e19a56a7a043a08d405e

**Comment by ssmirenkov** [comment]
Спасибо, помогло!!!!
