### ISSUE TITLE
Теги к новости из канала

### ISSUE THREAD

**Issue by ssmirenkov** [dle-modules/DLE-AutoRSS#2]
Здравствуйте!
Подскажите такой вопрос.
Как я понимаю модуль берет из rss канал тег category и его прописывает в теги.
Заметил что он берет только одну, первую категорю, но в некоторых новостях прописаны несколько.
Так и должно быть что берется только одна, перавя, категория? И как можно сделать что бы модуль брад их все?

Спасибо!

**Comment by pafnuty** [comment]
Теги получаются с помощью метода [get_category](https://github.com/dle-modules/DLE-AutoRSS/blob/master/upload/autorss.php#L318), я не разбирался как там это происходит внутри.
Попробуйте использовать метод [get_categories](https://github.com/dle-modules/DLE-AutoRSS/blob/master/upload/engine/modules/autorss/library/SimplePie.php#L2042), и обрабатывать полученные данные как массив.
